# Generated by Django 3.2.17 on 2024-03-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('occurrence_date_time', models.DateTimeField()),
                ('address', models.TextField()),
                ('lost_document', models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('ghana_card', 'Ghana Card'), ('other', 'Other')], max_length=100)),
                ('other_document_details', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
