# Generated by Django 3.2.17 on 2024-03-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.TextField()),
                ('reason_type', models.CharField(blank=True, choices=[('employment', 'Employment Background Check'), ('visa', 'Visa Application'), ('volunteer', 'Volunteer Work'), ('other', 'Other')], max_length=20)),
                ('documents', models.FileField(blank=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
