# Generated by Django 3.2.17 on 2024-03-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='expiry_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='identification_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='issue_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='lost_document',
            field=models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('ghana_card', 'Ghana Card'), ('voter_id_card', 'Voter ID Card')], max_length=100),
        ),
    ]
