# Generated by Django 3.2.17 on 2024-03-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
