# Generated by Django 3.2.17 on 2024-03-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police_report', '0002_alter_application_reason_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
    ]
