# Generated by Django 3.2.17 on 2024-03-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_report', '0002_alter_application_lost_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='lost_document',
            field=models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('ghana_card', 'Ghana Card'), ('voter_id_card', 'Voter ID Card')], max_length=100),
        ),
    ]
