# Generated by Django 3.2.17 on 2024-03-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_report', '0002_auto_20240323_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='other_document_details',
        ),
        migrations.AddField(
            model_name='application',
            name='house_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
