# Generated by Django 3.2.17 on 2024-03-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_report', '0003_alter_application_lost_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='expiry_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='identification_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='issue_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
