# Generated by Django 3.2.17 on 2024-03-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police_report', '0003_remove_application_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='reason_type',
        ),
    ]
