# Generated by Django 3.2.17 on 2024-03-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_report', '0004_auto_20240323_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='identification_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
